# Generated by Django 4.0.3 on 2022-05-30 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Searchresult',
            fields=[
                ('recordID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('searchCode', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userDetails', models.TextField(max_length=200, null=True)),
                ('userPicture', models.ImageField(default='male.png', null=True, upload_to='Profiles')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
